seed: 42
num_envs: 256
#replicate_physics: False
#scene:
#  replicate_physics: False
# this is the parameters for the BroNet shared model
models:
  force_encoding: None
  critic:
    n: 2
    latent_size: 512
  actor:
    n: 2
    latent_size: 512

agent:
  class: PPO
  rollouts: 75
  learning_epochs: 2
  mini_batches: 32 #500 # 128 steps / minibatch
  discount_factor: 0.99
  lambda: 0.99 #0.95
  learning_rate: 1.0e-04

  # below are not args
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 0.5 #1.0
  ratio_clip: 0.2
  clip_predicted_values: False #True
  #value_clip: 0.0 #0.2
  entropy_loss_scale: 0.000005
  value_loss_scale: 0.5 #1.0
  kl_threshold: 0.05 #0.0
  rewards_shaper_scale: 1.0
  time_limit_bootstrap: False

  # logging and checkpoint
  experiment:
    directory: "FPiH_franka"
    experiment_name: "default_BroNet_franka"
    write_interval: 150
    checkpoint_interval: 3000

videos:
  record_training: True
  training_interval: 925
  record_eval: True


defaults:
  - override hydra/job_logging: custom